# Site settings
title:          Homebush
description:    "Homebush: Where Life Stories Unfold"
url:            https://https://weshouldask.github.io/

# Author
author:
  name:         Sein L
  email:        seinlim@outlook.com
  url:          https://weshouldask.github.io/homebush

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: seinlim@outlook.com
  github: https://weshouldask.github.io
 # twitter: https://twitter.com
 # linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
