# Site settings
title:          Homebush - Where Life Stories Unfold
description:    "Welcome to a journey of growth and discovery with a twist of humor and wisdom. Here, a mid-aged man embarks on an adventure in homeschooling, shares the warmth of baking, and unveils clever life hacks. It's a candid chronicle of failures and satisfactions, a testament to the fact that learning and laughter don't have an age limit. Dive into the stories that make life a little more interesting and a lot more fun."
url:            https://https://weshouldask.github.io/

# Author
author:
  name:         Sein L
  email:        seinlim@outlook.com
  url:          https://weshouldask.github.io/homebush

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Related posts settings
related_posts_section:
  max_count:        5
  min_common_tags:  2

# Links to social media
social:
  email: seinlim@outlook.com
  github: https://weshouldask.github.io
 # twitter: https://twitter.com
 # linkedin: https://ba.linkedin.com/in/inela-avdic-hukic-322354131
